name: "Setup"
description: "Setup dependencies required to run any scripts using @tahminator/pipeline"

inputs:
  SECRETS:
    description: "Pass toJSON(secrets) from the calling workflow to expose all secrets as env vars."
    required: false
    default: ""
  GITHUB_TOKEN:
    description: "GitHub token used to send message"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./actions/setup
      with:
        GITHUB_SCRIPTS_DIR: "."
        SECRETS: ${{ inputs.SECRETS }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
