# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: CI
run-name: Running continuous deployment on ${{ github.actor }}'s commits

permissions:
  id-token: write
  contents: read

concurrency:
  group: cd
  cancel-in-progress: false

on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  buildAndDeploy:
    name: Build @tahminator/pipeline and deploy to NPM
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pipeline
        uses: ./.github/composite/setup

      # to be used for npm publish via OIDC
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"

      - name: Build
        run: bun run build

      - name: Upload to NPM
        run: bun run ./src/internal/upload-npm

  testAndbuildAndDeployBeta:
    name: Test package, build @tahminator/pipeline and deploy beta version to NPM
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pipeline
        uses: ./.github/composite/setup
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      # to be used for npm publish via OIDC
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25"

      - name: Build
        run: bun run test

      - name: Build
        run: bun run build

      - name: Upload beta tag to NPM
        run: bun run ./src/internal/upload-npm/beta --sha=${{ github.event.pull_request.head.sha }} --prId=${{ github.event.pull_request.number }}
